language: python
#python version
python: 3.8.6 
#define dependencsy
install:
  - pip install -r requirements.txt
#tests
script: ./scripts/unit-testing.sh
# allowed only these branch
branches:
  only:
  - master
  - develop
  - feature_structure_code
