
NAME_REPORT_FILE="report_"
DATE_FORMAT="%Y-%m-%d-%H"
EXTENSION_FINAL_FILE=".csv"
AUTHORIZATION_FILE="a"
SUMMARY_FINAL_FILE="NAME;DIRECTORY;EXTENSION;WEIGTH;TIMESTAMP\n"


CODE_ERROR_PROGRAM=2

DEFAULT_SEPARATOR=";"
